name: CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    name: Setup Node env

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

  tests:
    name: Run tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn test

  lint:
    name: Run lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn lint

  build-and-deploy:
    # only deploy if this is not running in a PR
    if: ${{ success() && github.event_name !== 'pull_request' }}
    name: Build and Deploy
    needs: ['tests', 'lint']
    steps:
      - name: Build
        run: yarn build

      - name: Deploy on GitHub Pages
      - run: git config --global user.name $user_name
      - run: git config --global user.email $user_email
      - run: git remote set-url origin https://${github_token}@github.com/${repository}
      - run: yarn deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACCESS_TOKEN_FOR_DEPLOY }}
          repository: ${{ github.repository }}
