name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI flow
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/base_setup
      - uses: ./.github/workflows/base_quality
